# Generated by Django 3.0.1 on 2019-12-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191229_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pouzivatelprofil',
            name='photo',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='produkt',
            name='obrazok',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
